FrameworkEnterprise_ProjectUas_Kelompok4/Controllers/LotController.cs
using FrameworkEnterprise_ProjectUas_Kelompok4.Data;
using FrameworkEnterprise_ProjectUas_Kelompok4.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FrameworkEnterprise_ProjectUas_Kelompok4.Controllers;

[Authorize]
public class LotController : Controller
{
    private readonly DatabaseContext _context;

    public LotController(DatabaseContext context, HttpContext httpContext)
    {
        _context = context;
    }

    // GET: Lot
    public async Task<IActionResult> Index()
    {
        if (_context.Lot == null)
            Problem("Entity set 'DatabaseContext.Lot'  is null.");

        var lots = await _context.Lot.Include(a => a.Agen).ToListAsync();

        return View(lots);
    }

    // GET: Lot/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Lot == null) return NotFound();

        var lot = await _context.Lot
            .FirstOrDefaultAsync(m => m.Id == id);
        if (lot == null) return NotFound();

        return View(lot);
    }

    // GET: Lot/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Lot/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(
        [Bind("Id,Berat,Deskripsi,StatusSortir,Tanggal")]
        Lot lot)
    {
        if (ModelState.IsValid)
        {
            var claimUser = HttpContext.User;

            // Get ID from claim
            var idUser = claimUser.Claims.FirstOrDefault(c => c.Type == "Id")?.Value;
            if (idUser == null) return NotFound();

            lot.Agen = await _context.User.FindAsync(int.Parse(idUser));


            _context.Add(lot);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        return View(lot);
    }

    // GET: Lot/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Lot == null) return NotFound();

        var lot = await _context.Lot.FindAsync(id);
        if (lot == null) return NotFound();
        return View(lot);
    }

    // POST: Lot/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id,
        [Bind("Id,Berat,Deskripsi,StatusSortir,Tanggal")]
        Lot lot)
    {
        if (id != lot.Id) return NotFound();


        // return RedirectToAction(nameof(Index));

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(lot);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LotExists(lot.Id))
                    return NotFound();
                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        return View(lot);
    }

    // GET: Lot/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Lot == null) return NotFound();

        var lot = await _context.Lot
            .FirstOrDefaultAsync(m => m.Id == id);
        if (lot == null) return NotFound();

        return View(lot);
    }

    // POST: Lot/Delete/5
    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_context.Lot == null) return Problem("Entity set 'DatabaseContext.Lot'  is null.");
        var lot = await _context.Lot.FindAsync(id);
        if (lot != null) _context.Lot.Remove(lot);

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool LotExists(int id)
    {
        return (_context.Lot?.Any(e => e.Id == id)).GetValueOrDefault();
    }
}

FrameworkEnterprise_ProjectUas_Kelompok4/Views/Partial/_Footer.cshtml
@{
}

<footer
    class="flex items-center px-6  bg-gradient-to-r from-white to-gray-100 flex-shrink-0"
    style="height: var(--footer-height);">
    <div class="text-slate-700 text-sm font-medium flex gap-2">
        <span> Sistem Manajemen Ekspor PT RBB &copy; </span>
        <span>|</span>
        <span>Dikembangkan oleh Kelompok 4</span>
        <span>|</span>
        <span>2023</span>
    </div>
</footer>

FrameworkEnterprise_ProjectUas_Kelompok4/Views/Partial/_HeadData.cshtml
@model dynamic

<link rel="icon" href="@Url.Content("/images/logo.jpg")"/>

<script>
    window.console.warn = () => null
</script>

<script src="https://cdn.tailwindcss.com"></script>

<!-- Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.cdnfonts.com/css/poppins" rel="stylesheet">

<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
<!-- Chart JS -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<!-- GSAP -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.3/gsap.min.js" integrity="sha512-7Au1ULjlT8PP1Ygs6mDZh9NuQD0A5prSrAUiPHMXpU6g3UMd8qesVnhug5X4RoDr35x5upNpx0A6Sisz1LSTXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- JQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!-- Data Tables -->
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">

<!-- CKEditor -->
<script src="https://cdn.ckeditor.com/ckeditor5/40.2.0/classic/ckeditor.js"></script>

<!-- CustomCss -->
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>

<!-- SweetAlert2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<style>
	* {
		font-family: 'Poppins', sans-serif;
	}
</style>

<script >
	// Tailwind CSS Config
	window.tailwind.config = {
		theme: {
			extend: {
				colors: {
					primary: '#845570'
				},
			}
		},
	}
</script>

<script>
	gsap.from('#content-wrapper', {
    			opacity: .5,
    			duration: 1,
    			y: 64,
    			ease: 'power2.out'
    		})
</script>

FrameworkEnterprise_ProjectUas_Kelompok4/Views/Partial/_Header.cshtml
@using System.Security.Claims
@{
}

<header
    class=" bg-gradient-to-r from-white to-gray-100 flex-shrink-0 px-6 flex items-center justify-between relative z-10"
    style="height: var(--header-height);">
    <h1 class="text-xl font-bold">
        <span class="font-medium">Halo</span> @User.FindFirstValue("Nama_Lengkap")!
    </h1>

    <div class="text-sm font-medium text-slate-700">
        <span class="font-bold">
            @User.FindFirstValue("Role")
        </span> PT RBB
    </div>
</header>

FrameworkEnterprise_ProjectUas_Kelompok4/Views/Partial/_Sidebar.cshtml
@using System.Security.Claims
@{
    var role = User.FindFirstValue("Role");
}

<aside class="w-64 h-screen border-slate-200 bg-white z-10 flex-shrink-0 flex flex-col">
    <img src="@Url.Content("/images/better-logo.png")" alt="Logo"/>

    <div class="grow ml-4 mb-4 flex flex-col gap-2 overflow-y-auto">
        <a
            href="/"
            class="hover:bg-gray-100 transition-colors py-4 px-6 rounded-lg text-lg font-medium flex items-center gap-3">
            <div class="w-6 h-6 grid place-items-center">
                <i class="fa-solid fa-home text-slate-700"></i>
            </div>
            <span>Dashboard</span>
        </a>

        @if (role == "Admin")
        {
            <a
                href="/users"
                class="hover:bg-gray-100 transition-colors py-4 px-6 rounded-lg text-lg font-medium flex items-center gap-3">
                <div class="w-6 h-6 grid place-items-center">
                    <i class="fa-solid fa-user text-slate-700"></i>
                </div>
                <span>Users</span>
            </a>
        }

        @if (role is "Admin" or "Manajer")
        {
            <a
                href="/ekspor"
                class="hover:bg-gray-100 transition-colors py-4 px-6 rounded-lg text-lg font-medium flex items-center gap-3">
                <div class="w-6 h-6 grid place-items-center">
                    <i class="fa-solid fa-truck text-slate-700"></i>
                </div>
                <span>Ekspor</span>
            </a>
        }


        @if (role is "Admin" or "Inventory" or "Manajer")
        {
            <a
                href="/sorting"
                class="hover:bg-gray-100 transition-colors py-4 px-6 rounded-lg text-lg font-medium flex items-center gap-3">
                <div class="w-6 h-6 grid place-items-center">
                    <i class="fa-solid fa-sort text-slate-700"></i>
                </div>
                <span>Sorting</span>
            </a>
        }

        @if (role is "Admin" or "Manajer" or "Agen")
        {
            <a
                asp-controller="Lot"
                asp-action="Index"
                class="hover:bg-gray-100 transition-colors py-4 px-6 rounded-lg text-lg font-medium flex items-center gap-3">
                <div class="w-6 h-6 grid place-items-center">
                    <i class="fa-solid fa-box text-slate-700"></i>
                </div>
                <span>Lot</span>
            </a>
        }

        <div class="mt-auto"></div>

        <a
            asp-controller="Auth"
            asp-action="LogOut"
            class="hover:bg-gray-100 transition-colors py-4 px-6 rounded-lg text-lg font-medium flex items-center gap-3">
            <div class="w-6 h-6 grid place-items-center">
                <i class="fa-solid fa-sign-out text-slate-700"></i>
            </div>
            <span>Keluar</span>
        </a>
    </div>
</aside>